### ISSUE TITLE
Request to add capability

### ISSUE THREAD

**Issue by sam-suresh** [iarenaza/moodle-local-notifyemailsignup#1]
If possible please add capability `notifyregistrations` so we can add this to any role other than administrators.

**Comment by iarenaza** [comment]
Hi @sam-suresh 

I'm not sure I understand your request. This plugin doesn't use roles for anything. It doesn't even have the concept of a capability (permission), as all the resources it uses (language strings and the list of authentication plugins that are enabled and support signups) are already covered by existing capabilities and roles in Moodle. This plugins simply uses whatever is already configured in those resources.

Can you clarify a bit what you are trying to achieve?

Saludos.

Iñaki.
